// export const metadata = {
//   title: "about",
//   description: "Generated by create next app",
// };
//another way
export function generateMetadata() {
  return { title: "about page", description: "Generated by create next app" };
}

export default function about() {
  return <>About</>;
}
